name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Frontend - install and build
        working-directory: frontend
        run: |
          npm ci || npm install
          npm run build --if-present

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Backend - install and check
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m compileall .

